/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoadatos.*;
import entidades.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Veronica
 */
public class AluPorMateVista extends javax.swing.JInternalFrame {
    private AlumnoData ad = new AlumnoData();
    private MateriaData md = new MateriaData();
    private InscripcionData id = new InscripcionData();
    private DefaultTableModel modelo = new DefaultTableModel();
    /**
     * Creates new form AluPorMateVista
     */
    public AluPorMateVista() {
        initComponents();
        cargaAlumnos();
        armaCabecera();
       // llenarTabla();
    }
    
    private void borrarFilas(){
    int filas = modelo.getRowCount()-1;
    for(int i=filas;i>=0;i--){
        modelo.removeRow(i);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbSA = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();
        jlFondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(530, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcbSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSAActionPerformed(evt);
            }
        });
        getContentPane().add(jcbSA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 240));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 10, 80, -1));

        jlFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gradient_2.jpg"))); // NOI18N
        jlFondo.setPreferredSize(new java.awt.Dimension(5300, 4000));
        getContentPane().add(jlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jcbSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSAActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        llenarTabla();
    }//GEN-LAST:event_jcbSAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Materia> jcbSA;
    private javax.swing.JLabel jlFondo;
    // End of variables declaration//GEN-END:variables
 
    private void cargaAlumnos() {
       List<Materia>materias=md.ListarMaterias();
       for(Materia materia:materias){
           jcbSA.addItem(materia);
       }
    }
    
        private void armaCabecera() {
    ArrayList<Object>titulos = new ArrayList();
    titulos.add("ID Alumno");
    titulos.add("DNI");
    titulos.add("Apellido");
    titulos.add("Nombre");
    
    for(Object titulo:titulos){
        modelo.addColumn(titulo);
    }
    jTable1.setModel(modelo);
    }

        private void llenarTabla(){
  
    Materia materiaSeleccionada = (Materia)jcbSA.getSelectedItem();
    List<Alumno> alumnos = id.listarAlumnosPorMateria(materiaSeleccionada.getIdMateria());   
      
        for(Alumno a:alumnos){
            modelo.addRow(new Object[]{a.getIdAlumno(),a.getDni(),a.getApellido(),a.getNombre()});
        } 
    
}
        
}
